### PR TITLE
Fix: back button navigates to correct list page (#318)

### LINKED ISSUE #318: Back button sends to wrong url
### Summary

from opportunity or volunteer profile the back button should send to the opp or volunteers lists

### Steps to Reproduce

Image

### Expected Behavior

send to lists 
https://app.need4deed.org/de/dashboard/volunteers in case of volunteer profile
or
 https://app.need4deed.org/de/dashboard/opportunities in case of opportunity profile

### Actual Behavior

sends to https://app.need4deed.org/en/dashboard 

### Environment

_No response_

### PR DESCRIPTION
**Pull request by lourooo**
Fix: back button navigates to correct list page (#318)

## Description
The back button in volunteer, opportunity and agent profiles was navigating to the wrong URL. It was always sending the user to the generic dashboard instead of the correct list page.

## Related Issues
Closes #318 

## Changes
- Back button in volunteer profile now navigates to `/dashboard/volunteers`
- Back button in opportunity profile now navigates to `/dashboard/opportunities`
- Back button in agent profile now navigates to `/dashboard/agents`

## Screenshots / Demos

https://github.com/user-attachments/assets/5a559d47-0a68-4bdd-9439-1a450214810e

## Checklist
- [ ] WITHIN THE SCOPE OF AN ISSUE; No unnecessary files included
- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] CI passes

### CODE REVIEW

File: src/components/Dashboard/Profile/ProfilePage.tsx [hunk 1]
```diff
@@ -10,9 +10,16 @@ const ProfilePage = (props: ProfileEntityProps) => {
...
+    "volunteer" in props
+      ? `/${i18n.language}/dashboard/volunteers`
+      : "opportunity" in props
+        ? `/${i18n.language}/dashboard/opportunities`
+        : `/${i18n.language}/dashboard/agents`;
+
   return (
     <PageContainer>
-      <BackLink href={`/${i18n.language}/dashboard`}>
+      <BackLink href={backHref}>
```
Comment (DarrellRoberts) [inline src/components/Dashboard/Profile/ProfilePage.tsx]: I would suggest instead
```typescript
href="."
```

File: src/components/Dashboard/Profile/ProfilePage.tsx [hunk 2]
```diff
@@ -10,9 +10,16 @@ const ProfilePage = (props: ProfileEntityProps) => {
   const { t, i18n } = useTranslation();
   const { sections, heading, header } = useProfileSections(props);
 
+  const backHref =
```
Comment (DarrellRoberts) [inline src/components/Dashboard/Profile/ProfilePage.tsx]: this could be hard to maintain and can cause bugs (if dashboard links change or we add more dashboard links).

**Review by DarrellRoberts — CHANGES_REQUESTED** [review]
I suggested something a bit more dynamic which will make the 
`const backHref` unneccessary

**Review by DarrellRoberts — APPROVED** [review]
thank you!
