### PR TITLE
Fix: Opportunity card: Schedule- Date time selection in case of event type #259

### LINKED ISSUE #259: Opportunity card: Schedule- Date time selection in case of event type
### Description

Problem: The opportunity type event has no option to select a date and time (similar to accompany type) but only regular days in a week (similar to reoccurring volunteering). https://www.figma.com/design/9Kl17OiDLbWoNxgY43Rgjk/Need4Deed-Designs-2025?node-id=10548-245533&t=Jh07Q73olAEHS4jH-4  

Image
 

### Proposed solution

 The same date time structure in the accompanying section should be replacing the scheudle section days-hours option when it comes to event type volunteering. https://www.figma.com/design/9Kl17OiDLbWoNxgY43Rgjk/Need4Deed-Designs-2025?node-id=14854-54563&t=Jh07Q73olAEHS4jH-4 

Image

### PR DESCRIPTION
**Pull request by lourooo**
Fix: Opportunity card: Schedule- Date time selection in case of event type #259

## Description
For event-type opportunities, the recurring weekly schedule (AvailabilityGrid) is replaced by a date and time picker inside the "Opportunity details" section, following the AccompanyingDetails pattern.

## Related Issues
Closes #259 

## Changes
- `OpportunityDetailsDisplay`: show event date and time fields instead of schedule for event-type opportunities
- `OpportunityDetailsEdit`: show date picker + time input instead of AvailabilityGrid for event-type opportunities
- `opportunityDetailsSchema`: added `eventDate` and `eventTime` fields; made `availability` optional for event types
- `OpportunityDetails/styles`: added styled components for date/time fields (`DateFieldRow`, `TimeInput`, etc.)
- `DatePickerWithLabel`: text input now only accepts digits and auto-inserts dots (e.g. `11.05.2025`)
- Translations: added `eventDate` and `eventTime` keys to EN and DE

## Screenshots / Demos
Before:
image

After:
image

## Checklist
- [ ] WITHIN THE SCOPE OF AN ISSUE; No unnecessary files included
- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] CI passes

### CODE REVIEW

File: src/components/Dashboard/Profile/sections/OpportunityDetails/OpportunityDetailsEdit.tsx [hunk 1]
```diff
@@ -60,7 +65,9 @@ export function OpportunityDetailsEdit({ opportunity, onCancel }: Props) {
       numberOfVolunteers: String(opp.numberOfVolunteers ?? ""),
       mainCommunication: languagesToFormValues(generalLangs, t),
       residentsSpeak: languagesToFormValues(recipientLangs, t),
-      availability: apiToFormAvailability(opp.availability),
+      availability: isEventType ? null : apiToFormAvailability(opp.availability),
```
Comment (DarrellRoberts) [inline src/components/Dashboard/Profile/sections/OpportunityDetails/OpportunityDetailsEdit.tsx]: I think `undefined` is better than `null` here

**Review by DarrellRoberts — CHANGES_REQUESTED** [review]
looks good to me! Just one small suggestion & along with updating your branch

File: src/components/Dashboard/Profile/sections/OpportunityDetails/OpportunityDetailsEdit.tsx (hunk 1 above)
Comment (lourooo) [reply src/components/Dashboard/Profile/sections/OpportunityDetails/OpportunityDetailsEdit.tsx]: Ok thanks, I will fix it

**Review by DarrellRoberts — APPROVED** [review]
thank you!
