### PR TITLE
Fix: Accompanying details: add new row #386

### LINKED ISSUE #386: Accompanying details: add new row
### Description

Appointment language missing , it should be below languge to translate and should recieve info German or English or English/German or No translation needed

### Proposed solution

 it should be below languge to translate and should recieve info German or English or English/German or No translation needed

Image

### PR DESCRIPTION
**Pull request by lourooo**
Fix: Accompanying details: add new row #386

## Description
Adds a new "Appointment language" radio-list field to the Accompanying Details section, positioned below "Language to translate". The field is wired up to the PATCH request and ready for when the backend adds support.

## Related Issues
Closes #386 

## Changes
- Added `appointmentLanguage` field to the accompanying details schema
- Added radio-list with 4 fixed options: **German**, **English**, **English/German**, **No translation needed**
- Added field to both display and edit components
- Wired up to the PATCH request, ready for when the backend adds support
- Added translations (EN + DE)

## Screenshots / Demos
image

## Checklist
- [ ] WITHIN THE SCOPE OF AN ISSUE; No unnecessary files included
- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] CI passes

### CODE REVIEW

File: src/components/Dashboard/Profile/sections/AccompanyingDetails/AccompanyingDetailsEdit.tsx [hunk 1]
```diff
@@ -156,6 +154,37 @@ export const AccompanyingDetailsEdit = ({
             />
           )}
         />
+
+        <Controller
+          name="appointmentLanguage"
+          control={control}
+          render={({ field }: { field: ControllerRenderProps<AccompanyingDetailsFormData, "appointmentLanguage"> }) => {
+            const optionKeys = ["german", "english", "englishGerman", "noTranslation"];
```
Comment (DarrellRoberts) [inline src/components/Dashboard/Profile/sections/AccompanyingDetails/AccompanyingDetailsEdit.tsx]: Better to use `enum` values for static strings values.

So (for now) within `config/constants.ts` , create this:
```typescript
export enum AppointmentLanguages {
  GERMAN = "german",
  ENGLISH = "english",
  ENGLISH_GERMAN = "englishGerman",
  NO_TRANSLATION = "noTranslation",
}
```

And then import these in the array e.g `[AppointmentLanguages.GERMAN, ....]`

File: src/components/Dashboard/Profile/sections/AccompanyingDetails/AccompanyingDetailsEdit.tsx [hunk 2]
```diff
@@ -156,6 +154,37 @@ export const AccompanyingDetailsEdit = ({
...
+            const optionLabels = optionKeys.map((key) =>
+              t(`dashboard.opportunityProfile.accompanyingDetails.appointmentLanguageOptions.${key}`),
+            );
+            const keyToOptionLabel: Record<string, string> = Object.fromEntries(
+              optionKeys.map((key, i) => [key, optionLabels[i]]),
+            );
+            const labelToOptionKey: Record<string, string> = Object.fromEntries(
+              optionKeys.map((key, i) => [optionLabels[i], key]),
+            );
```
Comment (DarrellRoberts) [inline src/components/Dashboard/Profile/sections/AccompanyingDetails/AccompanyingDetailsEdit.tsx]: It would be better to raise up `const optionKeys` , `const optionLabels` , `const keyToOptionLabel` and `const labelToOptionKey` to the parent `AccompanyingDetails` and then use here as props

File: src/components/Dashboard/Profile/sections/AccompanyingDetails/AccompanyingDetailsEdit.tsx [hunk 3]
```diff
@@ -156,6 +154,37 @@ export const AccompanyingDetailsEdit = ({
...
+          render={({ field }: { field: ControllerRenderProps<AccompanyingDetailsFormData, "appointmentLanguage"> }) => {
+            const optionKeys = ["german", "english", "englishGerman", "noTranslation"];
+            const optionLabels = optionKeys.map((key) =>
+              t(`dashboard.opportunityProfile.accompanyingDetails.appointmentLanguageOptions.${key}`),
+            );
+            const keyToOptionLabel: Record<string, string> = Object.fromEntries(
+              optionKeys.map((key, i) => [key, optionLabels[i]]),
+            );
+            const labelToOptionKey: Record<string, string> = Object.fromEntries(
+              optionKeys.map((key, i) => [optionLabels[i], key]),
```
Comment (DarrellRoberts) [inline src/components/Dashboard/Profile/sections/AccompanyingDetails/AccompanyingDetailsEdit.tsx]: I would follow the same pattern as the `keyToLabel` in the parent. 

I would suggest something like this:
```typescript
  const optionKeys = [AppointmentLanguages.GERMAN, AppointmentLanguages.ENGLISH, AppointmentLanguages.ENGLISH_GERMAN, AppointmentLanguages.NO_TRANSLATION];

  const keyToOptionLabel: Record<string, string> = {};
  const labelToOptionKey: Record<string, string> = {};
  const optionLabels = [];
  optionKeys.forEach((lang) => {
    const tLabel = t(`dashboard.opportunityProfile.accompanyingDetails.appointmentLanguageOptions.${lang}`);
    optionLabels.push(tLabel);
    keyToOptionLabel[lang] = tLabel;
    labelToOptionKey[tLabel] = lang;
  });
````

That way you can handle it all within one forEach operation

**Review by DarrellRoberts — CHANGES_REQUESTED** [review]
Looks good and works well. Just added some comments in regards to making it cleaner and more efficient

**Comment by lourooo** [comment]
Thanks @DarrellRoberts for the comments, I will update the PR

**Comment by lourooo** [comment]
Updated!

**Comment by nadavosa** [comment]
Hey @DarrellRoberts, see changes applied — does it work?

File: src/components/Dashboard/Profile/sections/AccompanyingDetails/AccompanyingDetails.tsx [hunk 4]
```diff
@@ -42,6 +43,17 @@ export const AccompanyingDetails = forwardRef<EditableSectionRef, Props>(functio
     labelToKey[lang.title] = String(lang.id);
   });
 
+  const appointmentLanguageKeyToLabel: Record<string, string> = {};
+  const appointmentLanguageLabelToKey: Record<string, string> = {};
+  Object.values(AppointmentLanguages).forEach((key) => {
```
Comment (DarrellRoberts) [inline src/components/Dashboard/Profile/sections/AccompanyingDetails/AccompanyingDetails.tsx]: I would just store the values in an array e.g. `[AppointmentLanguages.ENGLISH, ...]` so that I wouldn't have to trigger the` Object.values()` method.

Nevertheless, if you still want to use it, it'd be better still to encapsulate it in a `const` , so:
```typescript
const appointLanguages = Object.values(AppointmentLanguages)
```

That way, you don't have to keep triggering the `Object.values()` method when you want to use an array method, such as on `line 53`

**Review by DarrellRoberts — CHANGES_REQUESTED** [review]
looks good, just one little nickpic. And once you've resolved the merge conflicts, it's good to go

**Comment by lourooo** [comment]
Updated

**Review by DarrellRoberts — APPROVED** [review]
awesome, thank you!
