### PR TITLE
#336: Fixes infinite testimonial fetch

### LINKED ISSUE #336: inifinite testimonials.json render/fetch
### Summary

On main landing page, testimonials is being repeatedly rerendered

### Steps to Reproduce

Go to "/" and open dev tools

### Expected Behavior

For it to only be rendered/fetched once

### Actual Behavior

Image

### Environment

_No response_

### PR DESCRIPTION
**Pull request by DarrellRoberts**
## Description
Replaced Server fetch with useQuery fetch in order to prevent infite requests

## Related Issues
Closes #336 

## Changes
- On `/Testimonials` removed `async` from component and fetch method
- Add `useQuery` fetch.  
- I did this because `<Landing>` component, the direct parent of `TestimonialSection` is a Client and it can't have a Server async component as its direct child. This is what triggered the infinite fetch
- By adding the `useQuery` it turns ´Testimonials´ into a client component 

## Screenshots / Demos
image

## Checklist
- [ ] WITHIN THE SCOPE OF AN ISSUE; No unnecessary files included
- [ ] Tests added/updated
- [ ] Documentation updated
- [ ] CI passes

### CODE REVIEW

File: src/components/Testimonials/Testimonials.tsx [hunk 1]
```diff
@@ -1,24 +1,31 @@
...
-  }
+export default function Testimonials({ lang }: { lang: Lang }) {
+  const {
+    data: testimonials,
+    isLoading,
+    error,
+  } = useQuery({
+    queryKey: ["testimonials", lang],
+    queryFn: () => fetchTestimonials(lang),
+    staleTime: 1000 * 60 * 60,
```
Comment (arturasmckwcz) [inline src/components/Testimonials/Testimonials.tsx]: please use constant here instead of hardcoded value

**Review by arturasmckwcz — APPROVED** [review]

File: src/components/Testimonials/Testimonials.tsx (hunk 1 above)
Comment (arturasmckwcz) [reply src/components/Testimonials/Testimonials.tsx]: pls check `src/config/constants.ts`. an hour seems like is too short, maybe a day or a couple of days.

Comment (DarrellRoberts) [reply src/components/Testimonials/Testimonials.tsx]: thanks for reviewing! Sure thing, I'll have a look & change it

Comment (DarrellRoberts) [reply src/components/Testimonials/Testimonials.tsx]: have updated it & gone for two days
